### PR TITLE
Removed hardcode / tabs -> spaces

### PR DESCRIPTION
**Pull request by Shtoyan**
# General changes

- Removed all hardcoded classes.
- Tabs -> x4 spaces.

upd: moved all other changes to other PR.

### CODE REVIEW

**Comment by poosh** [comment]
- Next time you decide to change whitespace or do some heavy edit/replace, please do it within a separate pull request. Otherwise, it is hard to review the changes. 
- I manually merged your first two commits: f548d2a, 1980e17. 
- Now you need to fetch upstream, then rebase the `somechanges` branch on the latest master. I'm not sure if github allows to do it within this pull request - maybe you need to close this and create another one. 
- Then I will review the rest of the changes.

**Comment by Shtoyan** [comment]
Didn't notice your comment... Will try it and inform you.

**Comment by Shtoyan** [comment]
I rebased my `master`, seems ok (maybe?).

**Comment by Shtoyan** [comment]
Recreating.

**Pull request closed without merging**
